### ISSUE TITLE
Lab reads like a codealong yet all the code is already there making it awkward to follow the examples

### ISSUE THREAD

**Issue by pajamaw** [pletcher/node-js-export-strategies#1]
If this is by design then that's fine, but it's a bit odd to follow along and say, "Look we have an error here" when in order to follow along you have to delete everything then copy and paste the examples going on.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
